Add, Remove, and Edit Functions
DarkxDev/To-Do-List pull request #2
Opened 2023-01-18 22:20 UTC by DarkxDev

- Added a new JavaScript file for the new functionality.
- Added `addTask`, `removeCompletedTasks`, and `editTask` functions.
- All changes are saved in local storage.

2023-01-18 23:03 UTC, Felix45 requested changes
Hi @DarkxDev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif" />

## Highlights :heavy_check_mark: 
- [ ] No linter errors :heavy_check_mark: 
- [ ] Clean code base :heavy_check_mark: 
- [ ] Git flow is correctly used :heavy_check_mark: 
- [ ] Descriptive pull request title and summary :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 23:03 UTC, Felix45 commented on src/toDoList.js
> +class ToDoList {
- [ Required ] Please consider adding a method to this class that can be used to delete a single `to-do` item by clicking on a `delete button ` as shown in the video below

## Todo video
https://www.youtube.com/watch?v=AcUd-_Yjjqg

## Video screenshot
![Screenshot from 2023-01-19 01-57-31](https://user-images.githubusercontent.com/16392046/213313748-d932b33c-6e8b-4e91-90d2-82b3082f327e.png)

## Your design
<img src="https://user-images.githubusercontent.com/16392046/213313856-1143f2ea-0cfc-4af4-b169-bf02976f8d2a.png"  width="375px" />

2023-01-19 17:16 UTC, Whoistolu requested changes
Hi @DarkxDev 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 20:47 UTC, prolajumokeoni approved these changes
Hi @DarkxDev 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 c
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 20:54 UTC, merged